In [28]:
import torch()

In [5]:
torch.Tensor()

{}

## 1. Initialization

In [29]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [30]:
t = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device=device)

In [31]:
print(t.dtype)
print(t.device)
print(t.requires_grad)
print(t.shape)

torch.float32
cpu
False
torch.Size([2, 3])


In [32]:
print(t.tolist())
print(t.numpy())
print(t.numpy().tolist())

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]


In [64]:
# generate certain numbers
print(torch.zeros((2,2)))
print(torch.ones(2,2))
print(torch.empty((2,2)))
print(torch.rand((3,3)))

# from here to here
print(torch.arange(1,9,2))
print(torch.linspace(0,1,10))

# generate diagonals
print(torch.eye(5,5))
print(torch.diag(torch.arange(1,8)))

# in_place random sampling
print(torch.empty(size=(1,5)).normal_(mean=19, std=2))
print(torch.empty(size=(1,5)).uniform_(17,19))

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[5.1951e-37, 0.0000e+00],
        [5.5475e-37, 0.0000e+00]])
tensor([[0.9811, 0.2760, 0.2714],
        [0.3984, 0.2554, 0.7883],
        [0.3411, 0.3783, 0.2105]])
tensor([1, 3, 5, 7])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[1, 0, 0, 0, 0, 0, 0],
        [0, 2, 0, 0, 0, 0, 0],
        [0, 0, 3, 0, 0, 0, 0],
        [0, 0, 0, 4, 0, 0, 0],
        [0, 0, 0, 0, 5, 0, 0],
        [0, 0, 0, 0, 0, 6, 0],
        [0, 0, 0, 0, 0, 0, 7]])
tensor([[18.3298, 18.7380, 16.0234, 21.3972, 21.3311]])
tensor([[17.4627, 17.5396, 18.0585, 18.8833, 17.9259]])


In [68]:
torch.FloatTensor(2,3)

tensor([[       nan, 0.0000e+00, 1.8314e+25],
        [6.9768e+22, 1.4312e+13, 1.1319e+21]])

In [58]:
torch.Tensor(2,3)

tensor([[-8.3953e-15,  4.5611e-41,  5.2021e-37],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [59]:
torch.tensor(2,3)

TypeError: tensor() takes 1 positional argument but 2 were given

In [60]:
torch.empty(2,3)

tensor([[-8.3953e-15,  4.5611e-41,  5.0917e-37],
        [ 0.0000e+00,         nan,  0.0000e+00]])

In [65]:
torch.Tensor(2,3).normal_(mean=27, std=3)

tensor([[23.1249, 28.8463, 23.4262],
        [26.0065, 31.6060, 28.5437]])

In [77]:
v = torch.FloatTensor(2,3)
print(v.dtype)
print(type(v))
print(v.type())

torch.float32
<class 'torch.Tensor'>
torch.FloatTensor


In [78]:
v.type(torch.complex32)

RuntimeError: "copy_" not implemented for 'ComplexHalf'

In [81]:
v

tensor([[-8.3953e-15,  4.5611e-41,  5.3690e-37],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [76]:
v.type()

'torch.FloatTensor'

In [83]:
v.storage()

 -8.395275577152694e-15
 4.561086371530847e-41
 5.368954218080973e-37
 0.0
 4.484155085839415e-44
 0.0
[torch.FloatStorage of size 6]

In [85]:
b = torch.tensor([1.,2.])
b.dtype

torch.float32

In [86]:
d = torch.arange(10)
indxs = [2,5,6]
d[indxs]

tensor([2, 5, 6])

In [87]:
z = torch.tensor([1,2,3,4,5,6])

In [90]:
u = torch.where(z%2==0, 2,1); u

tensor([1, 2, 1, 2, 1, 2])

In [91]:
u.unique()

tensor([1, 2])

In [94]:
f = torch.arange(9); f

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
f.view(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [96]:
f.shape

torch.Size([9])

In [103]:
f = f.reshape(3,3); f

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [102]:
f.shape

torch.Size([3, 3])

In [106]:
f.t_()

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [107]:
f

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [108]:
v1 = torch.rand(2,3)
v2 = torch.rand(2,3)
print(v1)
print(v2)

tensor([[0.1155, 0.8226, 0.8600],
        [0.4946, 0.7127, 0.7699]])
tensor([[0.0406, 0.4948, 0.9415],
        [0.7555, 0.2157, 0.8309]])


In [111]:
torch.cat((v1,v2), dim=1)

tensor([[0.1155, 0.8226, 0.8600, 0.0406, 0.4948, 0.9415],
        [0.4946, 0.7127, 0.7699, 0.7555, 0.2157, 0.8309]])

In [113]:
r = torch.rand(100, 4,6); r.shape

torch.Size([100, 4, 6])

In [114]:
r.reshape(100, -1).shape

torch.Size([100, 24])

In [115]:
n = torch.arange(9); n

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [123]:
torch.unsqueeze(n, 0).unsqueeze(1)

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8]]])